config/routes.rb
MedsApp::Application.routes.draw do
  root 'static_pages#home'
  resources :users
  resources :dailies, only: [:edit, :update]
  resources :sessions, only: [:create, :destroy, :new]

  match '/weekly', to: 'users#weekly', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  

end

app/models/daily.rb
class Daily < ActiveRecord::Base
	belongs_to :user
	default_scope -> { order('created_at ASC') }
	validates :user_id, uniqueness: { scope: :report_for }
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { email.downcase! }
	before_create :create_remember_token
	after_create :create_first_daily

	has_many :dailies, dependent: :destroy

	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
										uniqueness: { case_sensitive: false }
	validates :password, length: { minimum: 6 }

	has_secure_password

	def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  	def create_remember_token
  		self.remember_token = User.encrypt(User.new_remember_token)
  	end

  	def create_first_daily
  		self.dailies.create(report_for: Date.today)
  	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  include DailiesHelper
end

app/controllers/dailies_controller.rb
class DailiesController < ApplicationController
	before_action :get_daily, only: [:update, :edit]

	def edit
		session[:return_to] ||= request.referer
	end

	def update
		if @daily.update(daily_params)
			flash[:success] = "Report updated"
			redirect_to session.delete(:return_to)
		else
			render 'edit'
		end
	end

	private

		def daily_params
			params.require(:daily).permit(:am_weight, :am_systolic,
				:am_diastolic, :am_pulse, :am_temp, :am_meds, :miralax,
				:lunch_meds, :nap, :pm_meds, :pm_systolic, :pm_diastolic,
				:pm_pulse, :bedtime_meds, :bedtime)
		end

		def get_daily
			@daily = Daily.find(params[:id])
			redirect_to(root_url) unless @daily.user_id == current_user.id
		end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			sign_in user
		  redirect_back_or user
	  else
	  	flash.now[:error] = 'Invalid email/password combination'
	    render 'new'
		end
	end

	
  def destroy
    sign_out
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:update, :edit, :weekly]
  before_action :correct_user, only: [:update, :edit, :show]
  before_action :admin_user, only: [:destroy, :index]

  def new
  	@user = User.new
  end

  def show
  	@user = User.find(params[:id])
  end

	def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to PillBox!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def index
    @users = User.all
    render 'index'
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end

  def weekly
    @user = current_user
    @sunday = Date.today.beginning_of_week(:sunday)
    @sun_daily = current_user.dailies.find_by(report_for: @sunday)
    @monday = Date.today.beginning_of_week(:sunday) + 1.day
    @mon_daily = current_user.dailies.find_by(report_for: @monday)
    @tuesday = Date.today.beginning_of_week(:sunday) + 2.days
    @tues_daily = current_user.dailies.find_by(report_for: @tuesday)
    @wednesday = Date.today.beginning_of_week(:sunday) + 3.days
    @wed_daily = current_user.dailies.find_by(report_for: @wednesday)
    @thursday = Date.today.end_of_week(:sunday) - 2.days
    @thurs_daily = current_user.dailies.find_by(report_for: @thursday)
    @friday = Date.today.end_of_week(:sunday) - 1.day
    @fri_daily = current_user.dailies.find_by(report_for: @friday)
    @saturday = Date.today.end_of_week(:sunday)
    @sat_daily = current_user.dailies.find_by(report_for: @saturday)
  end

  private

  	def user_params
  		params.require(:user).permit(:name, :email, :password,
  																 :password_confirmation)
  	end

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user) || current_user.admin?
    end

    def admin_user
      redirect_to root_url unless signed_in?
      if signed_in?
        redirect_to user_path(current_user) unless current_user.admin?
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dailies_helper.rb
module DailiesHelper
	def basic_output(daily, attribute)
		if daily.nil? || daily[attribute].nil?
			""
		else
			daily[attribute]
		end
	end

	def time_output(daily, attribute)
		if daily.nil? || daily[attribute].nil?
			""
		else
			daily[attribute].strftime("%l:%M %p")
		end
  end

  def nap_output(daily)
  	if daily.nil? || daily[:nap].nil?
  		""
  	elsif daily[:nap] == true
  		"Yes"
  	else
  		"No"
  	end
  end

  def bp_output(daily, sys, dias)
  	if daily.nil? || (daily[sys].nil? && daily[dias].nil?)
  		""
  	elsif daily[sys].nil? && !daily[dias].nil?
  		" / #{daily[dias]}"
  	elsif !daily[sys].nil? && daily[dias].nil?
  		"#{daily[sys]} / "
  	else
  		"#{daily[sys]} / #{daily[dias]}"
  	end
	end

	def report_time(time)
		if time.nil?
			return ""
		else
			return time.strftime("%l:%M %p")
		end
	end

	def add_edit_button(daily)
		link_to "Edit", edit_daily_path(daily),
								class: "btn btn-primary" unless daily.nil?
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user?(user)
    user == current_user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dailies/edit.html.erb
<%= provide(:title, "PillBox | Today") %>

<h1>Edit Daily Report
	<div>
		<small>
			<%= Time.now.strftime("%A, %B %d, %Y") %>
		</small>
	</div>
</h1>

<div class="row">
	<div class="span4 offset4">
		<%= form_for(@daily) do |f| %>

			<%= f.label :am_weight, "AM Weight" %>
			<%= f.text_field :am_weight %>

			<%= f.label :am_systolic, "AM Systolic" %>
			<%= f.text_field :am_systolic %>

			<%= f.label :am_diastolic, "AM Diastolic" %>
			<%= f.text_field :am_diastolic %>

			<%= f.label :am_pulse, "AM Pulse" %>
			<%= f.text_field :am_pulse %>

			<%= f.label :am_temp, "AM Temperature" %>
			<%= f.text_field :am_temp %>

			<%= f.label :am_meds, "AM Medication" %>
			<%= f.time_field :am_meds %>

			<%= f.label :miralax %>
			<%= f.time_field :miralax %>

			<%= f.label :lunch_meds, "Lunch Medication" %>
			<%= f.time_field :lunch_meds %>

			<%= f.label :nap %>
			<%= f.radio_button :nap, true %>
			<%= f.label :nap, 'Yes', value: true, class: 'radio inline' %>
			<%= f.radio_button :nap, false %>
			<%= f.label :nap, 'No', value: false, class: 'radio inline' %>

			<%= f.label :pm_meds, "PM Medication" %>
			<%= f.time_field :pm_meds %>

			<%= f.label :pm_systolic, "PM Systolic" %>
			<%= f.text_field :pm_systolic %>

			<%= f.label :pm_diastolic, "PM Diastolic" %>
			<%= f.text_field :pm_diastolic %>

			<%= f.label :pm_pulse, "PM Pulse" %>
			<%= f.text_field :pm_pulse %>

			<%= f.label :bedtime_meds, "Bedtime Medication" %>
			<%= f.time_field :bedtime_meds %>

			<%= f.label :bedtime %>
			<%= f.time_field :bedtime %>

			<%= f.submit "Save", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		Written by <a href="http://twitter.com/spencerpmoran">Spencer Moran</a>.
	</small>
	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "PillBox", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <% if signed_in? %>
          	<li><%= link_to "Today",    root_path %></li>
          	<li><%= link_to "This Week", weekly_path %></li>
            <li><%= link_to "Users", users_path if current_user.admin? %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= render 'layouts/shim' %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<%= render 'layouts/header' %>
  <div class="container">
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
  </div>

</body>
</html>

app/views/shared/_daily_report.html.erb
<table class="table table-striped">
	<% today = current_user.dailies.last %>
	<tr><td>AM Weight:</td><td><%= today.am_weight %></td></tr>
	<tr><td>AM Blood Pressure:</td>
		<td><%= bp_output(today, :am_systolic, :am_diastolic) %></td></tr>
	<tr><td>AM Pulse:</td><td><%= today.am_pulse %></td></tr>
	<tr><td>AM Temperature:</td><td><%= today.am_temp %></td></tr>
	<tr><td>AM Medication:</td><td><%= report_time(today.am_meds) %></td></tr>
	<tr><td>Miralax</td><td><%= report_time(today.miralax) %></td></tr>
	<tr><td>Lunch Medication:</td><td><%= report_time(today.lunch_meds) %></td></tr>
	<tr><td>Nap:</td><td><%= nap_output(today) %></td></tr>
	<tr><td>PM Medication:</td><td><%= report_time(today.pm_meds) %></td></tr>
	<tr><td>PM Blood Pressure:</td><td><%= bp_output(today, :pm_systolic, :pm_diastolic) %></td></tr>
	<tr><td>PM Pulse:</td><td><%= today.pm_pulse %></td></tr>
	<tr><td>Bedtime Medication:</td><td><%= report_time(today.bedtime_meds) %></td></tr>
	<tr><td>Bedtime:</td><td><%= report_time(today.bedtime) %></td></tr>
	<tr><td><%= link_to "Edit", edit_daily_path(Daily.find_by(report_for:
					Date.today, user_id: current_user.id)), class: "btn btn-primary" %></td><td></td></tr>
</table>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<%= provide(:title, 'PillBox | About') %>

	<h1>About</h1>
	<p>Written by Spencer Moran to help his ailing Dad.</p>

app/views/static_pages/contact.html.erb
<%= provide(:title, "PillBox | Contact") %>
<h1>Contact</h1>
<p>You can reach me on <a href="http://twitter.com/spencerpmoran">Twitter</a>.</p>

app/views/static_pages/home.html.erb
<%= provide(:title, 'PillBox') %>

<% if signed_in? %>
	<h1>
		Daily Report
		<div>
			<small>
				<%= Time.now.strftime("%A, %B %d, %Y") %>
			</small>
		</div>
	</h1>
	<div class="row">
		<div class="span4 offset4">
			<%= render 'shared/daily_report' %>
		</div>
	</div>

<% else %>
	<div class="center hero-unit">
		<h1>PillBox</h1>
		<h2>Helping you manage your daily medical rountines.</h2>
		<%= link_to "Sign up now!", new_user_path, class: "btn btn-large btn-primary" %>
	</div>
<% end %>

app/views/users/edit.html.erb
<%= provide(:title, "Edit | #{@user.name}") %>
<h1>Update your profile</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>

			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.label :email %>
			<%= f.text_field :email %>

			<%= f.label :password %>
			<%= f.password_field :password %>

			<%= f.label :password_confirmation, "Confirm Password" %>
			<%= f.password_field :password_confirmation %>

			<%= f.submit "Save", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/index.html.erb
<%= provide(:title, "PillBox | Users") %>
<h1>All Users</h1>

<div class="row">
	<ul class="user-list">
		<% @users.each do |user| %>
			<% unless user.admin? %>
				<li>
						<%= link_to user.name, user %>
    				| <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
          <% end %>
				</li>
		<% end %>
	</ul>
</div>

app/views/users/new.html.erb
<%= provide(:title, "PillBox | Sign up") %>
<h1>Sign up</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>

			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.label :email %>
			<%= f.text_field :email %>

			<%= f.label :password %>
			<%= f.password_field :password %>

			<%= f.label :password_confirmation, "Confirm password" %>
			<%= f.password_field :password_confirmation %>

			<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, "PillBox | #{@user.name}") %>
<h1><%= @user.name %></h1>
<div class="row">
	<div class="span6 offset3">
		<p>You have <%= @user.dailies.count %> reports.<br />
		View your most recent report <%= link_to "here",	root_url %>.</p>
	</div>
</div>

app/views/users/weekly.html.erb
<%= provide(:title, "Weekly Report | #{@user.name}") %>
<h1>
	Weekly Report
	<div>
		<small>
			<%= (Time.now.beginning_of_week(:sunday)).strftime("%b %-d, %Y") %> to
			<%= (Time.now.end_of_week(:sunday)).strftime("%b %-d, %Y") %>
		</small>
  </div>
</h1>
<div class="row">
	<div class="span12">
		<table class="table table-striped">
			<tr>
				<td>&nbsp;</td>
				<td>Sun, <%= @sunday.strftime("%-m/%-e") %></td>
				<td>Mon, <%= @monday.strftime("%-m/%-e") %></td>
				<td>Tues, <%= @tuesday.strftime("%-m/%-e") %></td>
				<td>Wed, <%= @wednesday.strftime("%-m/%-e") %></td>
				<td>Thurs, <%= @thursday.strftime("%-m/%-e") %></td>
				<td>Fri, <%= @friday.strftime("%-m/%-e") %></td>
				<td>Sat, <%= @saturday.strftime("%-m/%-e") %></td>
			</tr>
			<tr>
				<td>AM Weight:</td>
				<td><%= basic_output(@sun_daily, :am_weight) %></td>
				<td><%= basic_output(@mon_daily, :am_weight) %></td>
				<td><%= basic_output(@tues_daily, :am_weight) %></td>
				<td><%= basic_output(@wed_daily, :am_weight) %></td>
				<td><%= basic_output(@thurs_daily, :am_weight) %></td>
				<td><%= basic_output(@fri_daily, :am_weight) %></td>
				<td><%= basic_output(@sat_daily, :am_weight) %></td>
			</tr>
			<tr>
				<td>AM Blood Pressure:</td>
				<td><%= bp_output(@sun_daily, :am_systolic, :am_diastolic) %></td>
				<td><%= bp_output(@mon_daily, :am_systolic, :am_diastolic) %></td>
				<td><%= bp_output(@tues_daily, :am_systolic, :am_diastolic) %></td>
				<td><%= bp_output(@wed_daily, :am_systolic, :am_diastolic) %></td>
				<td><%= bp_output(@thurs_daily, :am_systolic, :am_diastolic) %></td>
				<td><%= bp_output(@fri_daily, :am_systolic, :am_diastolic) %></td>
				<td><%= bp_output(@sat_daily, :am_systolic, :am_diastolic) %></td>
			</tr>
			<tr>
				<td>AM Pulse:</td>
				<td><%= basic_output(@sun_daily, :am_pulse) %></td>
				<td><%= basic_output(@mon_daily, :am_pulse) %></td>
				<td><%= basic_output(@tues_daily, :am_pulse) %></td>
				<td><%= basic_output(@wed_daily, :am_pulse) %></td>
				<td><%= basic_output(@thurs_daily, :am_pulse) %></td>
				<td><%= basic_output(@fri_daily, :am_pulse) %></td>
				<td><%= basic_output(@sat_daily, :am_pulse) %></td>
			</tr>
			<tr>
				<td>AM Temperature:</td>
				<td><%= basic_output(@sun_daily, :am_temp) %></td>
				<td><%= basic_output(@mon_daily, :am_temp) %></td>
				<td><%= basic_output(@tues_daily, :am_temp) %></td>
				<td><%= basic_output(@wed_daily, :am_temp) %></td>
				<td><%= basic_output(@thurs_daily, :am_temp) %></td>
				<td><%= basic_output(@fri_daily, :am_temp) %></td>
				<td><%= basic_output(@sat_daily, :am_temp) %></td>
			</tr>
			<tr>
				<td>AM Medication:</td>
				<td><%= time_output(@sun_daily, :am_meds) %></td>
				<td><%= time_output(@mon_daily, :am_meds) %></td>
				<td><%= time_output(@tues_daily, :am_meds) %></td>
				<td><%= time_output(@wed_daily, :am_meds) %></td>
				<td><%= time_output(@thurs_daily, :am_meds) %></td>
				<td><%= time_output(@fri_daily, :am_meds) %></td>
				<td><%= time_output(@sat_daily, :am_meds) %></td>
			</tr>
			<tr>
				<td>Miralax:</td>
				<td><%= time_output(@sun_daily, :miralax) %></td>
				<td><%= time_output(@mon_daily, :miralax) %></td>
				<td><%= time_output(@tues_daily, :miralax) %></td>
				<td><%= time_output(@wed_daily, :miralax) %></td>
				<td><%= time_output(@thurs_daily, :miralax) %></td>
				<td><%= time_output(@fri_daily, :miralax) %></td>
				<td><%= time_output(@sat_daily, :miralax) %></td>
			</tr>
			<tr>
				<td>Lunch Medication:</td>
				<td><%= time_output(@sun_daily, :lunch_meds) %></td>
				<td><%= time_output(@mon_daily, :lunch_meds) %></td>
				<td><%= time_output(@tues_daily, :lunch_meds) %></td>
				<td><%= time_output(@wed_daily, :lunch_meds) %></td>
				<td><%= time_output(@thurs_daily, :lunch_meds) %></td>
				<td><%= time_output(@fri_daily, :lunch_meds) %></td>
				<td><%= time_output(@sat_daily, :lunch_meds) %></td>
			</tr>
			<tr>
				<td>Nap:</td>
				<td><%= nap_output(@sun_daily) %></td>
				<td><%= nap_output(@mon_daily) %></td>
				<td><%= nap_output(@tues_daily) %></td>
				<td><%= nap_output(@wed_daily) %></td>
				<td><%= nap_output(@thurs_daily) %></td>
				<td><%= nap_output(@fri_daily) %></td>
				<td><%= nap_output(@sat_daily) %></td>
			</tr>
			<tr>
				<td>PM Medication:</td>
				<td><%= time_output(@sun_daily, :pm_meds) %></td>
				<td><%= time_output(@mon_daily, :pm_meds) %></td>
				<td><%= time_output(@tues_daily, :pm_meds) %></td>
				<td><%= time_output(@wed_daily, :pm_meds) %></td>
				<td><%= time_output(@thurs_daily, :pm_meds) %></td>
				<td><%= time_output(@fri_daily, :pm_meds) %></td>
				<td><%= time_output(@sat_daily, :pm_meds) %></td>
			</tr>
			<tr>
				<td>PM Blood Pressure:</td>
				<td><%= bp_output(@sun_daily, :pm_systolic, :pm_diastolic) %></td>
				<td><%= bp_output(@mon_daily, :pm_systolic, :pm_diastolic) %></td>
				<td><%= bp_output(@tues_daily, :pm_systolic, :pm_diastolic) %></td>
				<td><%= bp_output(@wed_daily, :pm_systolic, :pm_diastolic) %></td>
				<td><%= bp_output(@thurs_daily, :pm_systolic, :pm_diastolic) %></td>
				<td><%= bp_output(@fri_daily, :pm_systolic, :pm_diastolic) %></td>
				<td><%= bp_output(@sat_daily, :pm_systolic, :pm_diastolic) %></td>
			</tr>
			<tr>
				<td>PM Pulse:</td>
				<td><%= basic_output(@sun_daily, :pm_pulse) %></td>
				<td><%= basic_output(@mon_daily, :pm_pulse) %></td>
				<td><%= basic_output(@tues_daily, :pm_pulse) %></td>
				<td><%= basic_output(@wed_daily, :pm_pulse) %></td>
				<td><%= basic_output(@thurs_daily, :pm_pulse) %></td>
				<td><%= basic_output(@fri_daily, :pm_pulse) %></td>
				<td><%= basic_output(@sat_daily, :pm_pulse) %></td>
			</tr>
			<tr>
				<td>Bedtime Medication:</td>
				<td><%= time_output(@sun_daily, :bedtime_meds) %></td>
				<td><%= time_output(@mon_daily, :bedtime_meds) %></td>
				<td><%= time_output(@tues_daily, :bedtime_meds) %></td>
				<td><%= time_output(@wed_daily, :bedtime_meds) %></td>
				<td><%= time_output(@thurs_daily, :bedtime_meds) %></td>
				<td><%= time_output(@fri_daily, :bedtime_meds) %></td>
				<td><%= time_output(@sat_daily, :bedtime_meds) %></td>
			</tr>
			<tr>
				<td>Bedtime:</td>
				<td><%= time_output(@sun_daily, :bedtime) %></td>
				<td><%= time_output(@mon_daily, :bedtime) %></td>
				<td><%= time_output(@tues_daily, :bedtime) %></td>
				<td><%= time_output(@wed_daily, :bedtime) %></td>
				<td><%= time_output(@thurs_daily, :bedtime) %></td>
				<td><%= time_output(@fri_daily, :bedtime) %></td>
				<td><%= time_output(@sat_daily, :bedtime) %></td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td><%= add_edit_button(@sun_daily) %></td>
				<td><%= add_edit_button(@mon_daily) %></td>
				<td><%= add_edit_button(@tues_daily)  %></td>
				<td><%= add_edit_button(@wed_daily)  %></td>
				<td><%= add_edit_button(@thurs_daily)  %></td>
				<td><%= add_edit_button(@fri_daily)  %></td>
				<td><%= add_edit_button(@sat_daily)  %></td>
			</tr>
		</table>
	</div>
</div>